### ISSUE TITLE
memories:places-setup command without interaction ?

### ISSUE THREAD

**Issue by albundy83** [pulsejet/memories#1252]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use command line to setup memories and be able to repeat command.

Unfortunatelly, interactive seems mandatory when I run it a second time even if I use `-n` parameter:
```bash
ww-data@nextcloud:~/html$ php occ memories:places-setup -n
Attempting to set up reverse geocoding
Database support was detected

Database is already set up
This will drop and re-download the planet database
This is generally not necessary to do frequently 

Are you sure you want to download the planet database?
Proceed? [y/N] 
```

**Describe the solution you'd like**
I'd like to be able to force yes answer with common `-n` option

**Describe alternatives you've considered**
No alternative for moment

**Additional context**
nextcloud 29.0.4 in Kubernetes
memories 7.3.1

**Comment by akhil1508** [comment]
@pulsejet Could you also advise on if `occ memories:places-setup`  is safe to run while nextcloud is live?

**Comment by albundy83** [comment]
Well, I just follow the steps from here https://memories.gallery/config/ and by the way, my nextcloud is not running :)

**Comment by akhil1508** [comment]
@pulsejet @albundy83 So sorry to hijack this issue, maybe there is a better place for this question 

> Yeah, should have no issues.

But I'm updating memories to 7.3.1 from 6.2.2. Do I need to do an `occ memories:places-setup` even if I am using MariaDB? Will the feature stop working otherwise?

The [changelog](https://github.com/pulsejet/memories/blob/master/CHANGELOG.md#v702---2024-03-19) says "not MariaDB" explicitly:

>  Breaking: You must run occ memories:places-setup again after this update
>    Reverse geocoding lookups with Postgres/MySQL (not MariaDB) are now 100x faster

**Comment by pulsejet** [comment]
> But I'm updating memories to 7.3.1 from 6.2.2. Do I need to do an `occ memories:places-setup` even if I am using MariaDB? Will the feature stop working otherwise?

It's been a while, but IIRC you do need to run it again, otherwise it'll stop working. The performance improvement is only for MySQL and postgres (these had a bug that mariadb didn't, so they were slow)

@albundy83 that makes sense, for automated installation 👍🏻 
I'll still recommend not to re-run it unnecessarily since it drops the table and makes the same table again (the table it creates is actually read only, so this is pointless)

**Comment by albundy83** [comment]
So is it possible to have it respect the common `-n` parameter that we have usually with others oc xxx command ?

**Comment by pulsejet** [comment]
Yeah, as I mentioned this is a bug

**Comment by pulsejet** [comment]
Turns out this is already possible. You just need to use `--force` instead of `-n`

**Comment by albundy83** [comment]
Ah perfect, thanks a lot !!! :)
