### ISSUE TITLE
Cannot play .mov files uploaded from iOS camera roll

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#143]
This seems to be more of an issue on Firefox. Chrome will play the videos but they are glitchy - perhaps there's some kind of non-performant transcoding that needs to take place?

This is also an issue with Nextcloud Photos, so maybe it's out of the scope of the project, but if it could be fixed here, it would be a big improvement over the default photos app.

**Comment by meichthys** [comment]
![image](https://user-images.githubusercontent.com/10717998/199107588-d0dccb98-740b-4913-be3b-fe5d9e4a4c1e.png)

**Comment by pulsejet** [comment]
This is about browser video support, I believe. What we need is server-side transcoding.

Whether this is in scope for memories is a good question. Right now, memories is purely presenting the existing photos. If this is implemented it'll be a bit more than that (basically we reimplement nextcloud/viewer). But that is fine too. So I guess it depends on how much work this turns out to be.

**Comment by pulsejet** [comment]
With transcoding everything should be supported now, with the caveat that your server has enough horsepower.

**Comment by meichthys** [comment]
@pulsejet Could you elaborate on this a bit? Was transcoding added to nextcloud server/photos/files? or to memories?

**Comment by pulsejet** [comment]
Memories will bundle a transcoding server in the next version: https://github.com/pulsejet/memories/blob/master/CHANGELOG.md

It's already available in nightly, but might not be very stable.

**Comment by meichthys** [comment]
That's awesome! Can't wait to try it.
