### ISSUE TITLE
[Question] Playing Video: What is the difference between "Direct" and "Original"?

### ISSUE THREAD

**Issue by EVOTk** [pulsejet/memories#276]
Hello,

I don't really understand the difference between "Direct" and "Original". I excuse myself to open a ticket for this if it's a stupid question ^^'

![image](https://user-images.githubusercontent.com/45015615/206578064-e4c9406d-dabe-4726-b6f9-512fa7170abf.png)

**Comment by pulsejet** [comment]
Original will use the highest possible quality (including max resolution), **with transcoding and HLS**.
Direct will use just the actual file on disk and disable transcoding. This might not always work, e.g. if the video is HEVC.

**Comment by EVOTk** [comment]
Ha okay, I understand. Thanks

**Comment by siccovansas** [comment]
I had the same question. Are the terms "Direct" and "Original" also used like this in other video software/websites? If not, then I guess these terms can be improved and/or they need a description and/or better grouping.

To me "Original" can also sound like the original file without transcoding and "Direct" sounds like it will play/stream 'directly', while both are not the case :).

I guess "Original" is the preferred option, so maybe a "preferred" description can be added. For example the way YouTube has added the 'Enhanced bitrate' description. Or otherwise the description 'Streams directly'.
![Screenshot from 2024-10-15 13-58-09](https://github.com/user-attachments/assets/02d5d0f7-cda4-4158-8c4e-958241d642e5)

Another idea is grouping:
```
< Quality
------------------------
[] Auto
------------------------
[] Direct
------------------------
Streaming
[] Original (preferred)
[] 1080p HD
[] 720p HD
[] 480p HD
```
