### ISSUE TITLE
File Type Support instructions unclear

### ISSUE THREAD

**Issue by rourke** [pulsejet/memories#308]
I'm trying to follow the instructions here: https://github.com/pulsejet/memories/wiki/File-Type-Support but they are unclear to me.

First of all it mentions syntax like this:
```
  'enabledPreviewProviders' =>
  array (
    ... => 'OC\\Preview\\HEIC',
    ... => 'OC\\Preview\\TIFF',
  ),
```
This results in `ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /config/www/nextcloud/config/config.php:51`, so correct me if I'm wrong, but I think this is the correct syntax, and it works for me:

```
  'enabledPreviewProviders' =>
  array (
    'OC\\Preview\\HEIC',
    'OC\\Preview\\TIFF',
  ),
```

Second is the instructions for videos. It says I need to install `ffmpeg`, but it seems already available within the Nextcloud docker image. Perhaps it's good to mention this in the instructions? Also is it still needed to add the `memories.ffmpeg_path` config in this case? Is there some sort of fallback that checks if the default binary path `/usr/bin/ffmpeg` exists? Because for me there is no change between indexing with this config and without.

**Comment by jacksgt** [comment]
Hello,

there are two formats for declaring arrays in PHP. The simpler one is the one you have found working for you, the other one uses explicit indices:

```
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\PDF',
    5 => 'OC\\Preview\\Epub',
  ),
```

The documentation also refers to this format, but you should substitute the `...` with the appropriate array indices (`15`, `16`, ...).

Personally, I'm also using the "simpler" format (without indices) in my `config.php` and it works fine.
Maybe the docs should be updated, because also [Nextcloud's config.sample.php](https://github.com/nextcloud/server/blob/stable24/config/config.sample.php#L1174) uses the simpler format.
(I'm not a PHP dev, though).

**Comment by jacksgt** [comment]
> It says I need to install ffmpeg, but it seems already available within the Nextcloud docker image

Which Docker image are you using? I guess it's not the official one (`docker.io/llibrary/nextcloud`), because that one doesn't come with ffmpeg.
The `docker.io/linuxserver/nextcloud` image comes with ffmpeg, though.

**Comment by rourke** [comment]
Ah yes, I'm using `docker.io/linuxserver/nextcloud` it seems. Thanks for the information.

**Comment by pulsejet** [comment]
Updated. It should be obvious to use the associative array syntax if that's appropriate.
