### ISSUE TITLE
[Feature Request] Choose Sorting order

### ISSUE THREAD

**Issue by do-lorenz** [pulsejet/memories#371]
Hi there! 

First, thanks a lot for this gem. Was searching for something like this for a long time. Hope my small donation helps to keep you motivated. 

I think letting the user choose a sorting order would make a lot of difference, especially for folders and albums. When looking through your timeline, it makes sense to have the newest on top. But when looking at a album or folder, **you usually want to "re-live" the experience** (or memories :smile:) this event you created the folder/album for. Doing that in reverse is a bit weird for me. You also don't look at your real photo albums from back to front.

Proposed changes / feature could be one of the following:
- If only static change shall be performed, I would reverse the ordering from new -> old to old->new, but only for folders and albums.
- Setting for each point (Folder, Album, Timeline, Favourites, ...) can be set by the admin (my personal favourite)
- If a setting shall be created to let the individual user decide, I would be happy if a default could be set  by the admin. I usually take photos for a group of people (friends/family) and giving them access to the photos. I want to give them the best experience, instructing each one to change settings seems to be unrealistic.

**Comment by pulsejet** [comment]
* Albums are already sorted old -> new
* Having an option to do the same for Folders sounds like a good idea. This could be a per-user setting with a default. I believe many people simply use folders as albums.
* Not so sure about the rest of the views. Seems rather counter-intuitive to me to have the timeline sorted old -> new. Then you need to scroll all the way to the bottom to see the photo you took seconds ago ...

**Comment by do-lorenz** [comment]
Ah yeah, thats what I am doing. I have my photos sorted in Folders anyways, so I usually don't bother with also creating an album.

Yes, you are right, for the timeline, it doesn't make much sense. I suggested it for consistency, but on second thought, it wasn't a bright moment :)

thanks for adding it to the milestone!

**Comment by jacotec** [comment]
> * Albums are already sorted old -> new

I was about to create a feature request for that right now when I found this one :-)

The above is the issue for me ... I'd like to have albums also sorted new --> old, like the timeline. Or, at best, configurable per user or per album.

**Comment by GitWidi** [comment]
First of all: It is an insanely great job you did with this app. Thus, **a big thank to you**!

> Albums are already sorted old -> new
> Having an option to do the same for Folders sounds like a good idea.

Oh yes, that would be great. I wish to extend this feature to the sorting of **public shared links** too.

To understand my feature wish, here my szenario:

- I organize hiking trips for small groups. The participants are changing. So, I don't want to add an account for each of them.
- Afterwards I create a common photo album where all participants can upload their pictures, view and download the entire pictures of all participants. When viewing the "album" it would be nice if the pictures were displayed in chronological order. 
- So far, I create a folder for each tour and send my participants a public shared link (upload only) to upload their pictures. 
- A second public shared link (view and download, e.g.: https://cloud.domain.tld/apps/memories/s/LINK_TOKEN) is used to view the pictures in the "photo album" and download them if needed. 
- An album (in terms of the app Photos) is impractical for this, as all images must be entered into the album individually. But I don't know when or who uploads any pictures to the folder. 

Until NC 19 (or thereabouts) this worked very well with the app [Gallery](https://github.com/nextcloud/gallery) - until NC 23 it still worked with a few workarounds, but since NC 24 I unfortunately can't get this app to work anymore. 

Thanks and regards,
Friedbert

**Comment by fcrozat** [comment]
> > * Albums are already sorted old -> new
> 
> I was about to create a feature request for that right now when I found this one :-)
> 
> The above is the issue for me ... I'd like to have albums also sorted new --> old, like the timeline. Or, at best, configurable per user or per album.

I concur with this one, specially when sharing an album where photos are added on a regular basis and people expect to have the latest photos at the top.

**Comment by RikkiBC** [comment]
> > > * Albums are already sorted old -> new
> > 
> > 
> > I was about to create a feature request for that right now when I found this one :-)
> > The above is the issue for me ... I'd like to have albums also sorted new --> old, like the timeline. Or, at best, configurable per user or per album.
> 
> I concur with this one, specially when sharing an album where photos are added on a regular basis and people expect to have the latest photos at the top.

This is my use case too, so I would adore seeing this feature developed.

Some albums are of an event, so having the default old to new sort is good.

However other albums are more used as a collection of people or places, e.g developments on our property, or pics of our family animals over the many years. In these cases, having them sorted new to old is much preferred.

**Comment by shperrung** [comment]
> * Albums are already sorted old -> new

Thanks a lot for this app.
As I see, sort old->new on History page is by file's latest modification date. Is it possible to change/add sort by Creation date from EXIF?

I'm doing some changes with videos (cut, stab...) and often these files are out of order on History page

**Comment by pulsejet** [comment]
> on History page

What History page? Screenshot?

**Comment by shperrung** [comment]
"Timeline" the first page.
In Russian it is another word.
Unfortunately, I can't find tool for batch change of modification/creation date for file from exif information. So, it would be great to have sort options.

**Comment by pulsejet** [comment]
Not sure, but could be a bug or missing feature in exiftool. But not related to this issue; please file a separate one.

**Comment by pulsejet** [comment]
This is now configurable:
1. "Treat folders as albums" will enable `old-->new` in folders (like albums)
2. "Timeline view" for albums will enable `new-->old` similar to the main timeline in albums
3. You can change the sort order of shared albums and folders simply by adding `?sort=album` or `?sort=timeline` at the end of the sharing URL.

![image](https://user-images.githubusercontent.com/10709794/223884579-51444d43-d55f-4a5f-a907-627ff87bbb93.png)

**Comment by GitWidi** [comment]
Ohhh - THANK YOU. That sounds amazing.
