### ISSUE TITLE
transcoding with cuda results in black video if original has rotation 270

### ISSUE THREAD

**Issue by darkobas** [pulsejet/memories#394]
I noticed that some of my videos played with transcoder just show a black screen.

the command in log:
```
/usr/bin/ffmpeg -loglevel warning -hwaccel cuda -hwaccel_output_format cuda -autorotate 0 -i /mnt/smbshares/1/2022/08/VID20220817200832.mp4 -copyts -vf format=cuda,hwupload,scale_cuda=passthrough=0 -c:v h264_nvenc -profile:v high -preset p6 -tune ll -temporal-aq 1 -rc vbr -rc-lookahead 30 -cq 24 -c:a aac -ac 1 -b:a 192k -avoid_negative_ts disabled -f hls -hls_time 3 -force_key_frames expr:gte\(t,n_forced*3\) -hls_segment_type mpegts -start_number 0 -hls_segment_filename /tmp/test3max-%06d.ts -
```
produces a "portrait" video.
the original file has Rotation "270", but plays everywhere correctly... also the preview shows correct orientation.

edit:
jeez i think I know where the problem originates.. the file has wrong width height metadata
```
Source Image Width              : 1080
Source Image Height             : 1920
..
Video Frame Rate                : 29.953
Image Size                      : 1080x1920
```

**Comment by vitis586** [comment]
Did you ever sort this out? I guess that I am experiencing the same issue. It is not tied to CUDA. I am experiencing with VAAPI and also without HW acceleration. Any video in portrait mode is not converted correctly. My sample video shows the following in MediaInfo. So it is still 3840x2160 but rotated. I think that is what you also figured out. Memories show it correctly as 2160x3840.

> Width                                    : 3840
> Width                                    : 3 840pixely
> Height                                   : 2160
> Height                                   : 2 160pixely
> Sampled_Width                            : 3840
> Sampled_Height                           : 2160
> Pixel aspect ratio                       : 1.000
> Display aspect ratio                     : 1.778
> Display aspect ratio                     : 16:9
> Rotation                                 : 270.000
> Rotation                                 : 270°
> Frame rate mode                          : VFR
> Frame rate mode                          : Variable

I think that ffmpeg transcoder does not reflect this. The chunks that get generated during transcoding are with rotation of 0 deg. The rotation is not even in the headers or at least it is not shown by MediaInfo. Following is a screenshot from one of the 1080p chunks.

![obrazek](https://user-images.githubusercontent.com/55784861/236564180-69f723d2-53fa-4c90-80ff-3717ac7994be.png)

My command looks a bit different that yours but that might be due to my use of VAAPI.

`2023/05/05 18:45:54 clyo7t95td00-1080p: /usr/bin/ffmpeg -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -autorotate 0 -i /mnt/vitis/Fotky/1111_Telefon_zaloha/2023/01/PXL_20230120_152746581.mp4 -copyts -vf format=nv12|vaapi,hwupload,scale_vaapi=force_original_aspect_ratio=decrease:format=nv12:w=1920:h=1080 -profile:v main -maxrate 7080000 -bufsize 14160000 -map 0:v:0 -c:v h264_vaapi -global_quality 25 -map 0:a:0? -c:a aac -ac 1 -avoid_negative_ts disabled -f hls -hls_time 3 -force_key_frames expr:gte(t,n_forced*3) -hls_segment_type mpegts -start_number 0 -hls_segment_filename /tmp/transcode/ocda4msb35cj/clyo7t95td00-3654354349/1080p-%06d.ts -`

I can see that ffmpeg set the width and height to 1920 by 1080 which is fine but the autorotate is set to 0 which might be the mistake. My understanding is that `-autorotate 0` turns it off so ffmpeg then ignores the rotation metadata. Other option is that Pixel phones use some specific rotation metadata that are not interpreted correctly. I can try and play with the autorotate function. I can also supply a sample if @pulsejet is interested.

**Comment by pulsejet** [comment]
@vitis586 a sample would be useful

**Comment by vitis586** [comment]
Sample with 270deg rotation - https://drive.google.com/file/d/1VQgQArTKHtnphcZIEgJ_5PtEdBem2tkG/view?usp=sharing

Sample is from Pixel 7 Pro front camera. Rear camera portrait has rotation 90deg and that plays fine. iPhone 13 Pro shoots portrait video with 90deg rotation on both cameras. My friends has Galaxy S22 and that also shoots front portrait as 270deg, so it might be an Android thing. This defeats my autorotate theory.

**Comment by pulsejet** [comment]
Fixed, will close when merged to master.
