### ISSUE TITLE
NVENC with external go-vod?

### ISSUE THREAD

**Issue by travisboss** [pulsejet/memories#506]
Wondering how to configure this?  I currently have a P2000 installed on my Ubuntu-Server and am using it just fine in jellyfin with nvidia-docker.  Can this be used for memories and the external service go-vod?

I am using linuxserver/nextcloud which uses Alpine and does not have the option for NVENC.

Thanks.

**Comment by pulsejet** [comment]
I doubt there is any easy way to get the alpine images to work with NVIDIA.

I suggest either of:
1. Switch to the official debian image and add all the NVIDIA deps in it (custom Dockerfile)
2. Run go-vod externally with a custom Dockerfile for the drivers and ffmpeg build. This is the easier path. (https://github.com/pulsejet/memories/wiki/HW-Transcoding)

**Comment by travisboss** [comment]
On option 2. is there something I need to do with the go-vod config to make sure it uses the nvidia card?  That is where I am getting hung up on.

```
{
    "bind": "0.0.0.0:47788",
    "ffmpeg": "\/usr\/local\/bin\/ffmpeg",
    "ffprobe": "\/usr\/local\/bin\/ffprobe",
    "tempdir": "\/tmp\/go-vod"

    "vaapi": false,
    "vaapiLowPower": false,
    "nvenc": false,
    "nvencTemporalAQ": false,
    "nvencScale": "npp"
}
```

I saw this and the part of nvenc, but do I need to expose something to go-vod (gpu) to get it to work?

**Comment by pulsejet** [comment]
Yeah, you'll need to pass the GPU to the container + make sure all the drivers are present in the image (nvidia-smi should run) + ffmpeg is compiled to link with them.

I have zero experience with this, so maybe someone else can help.

This might be useful: https://jellyfin.org/docs/general/administration/hardware-acceleration/nvidia/

**Comment by travisboss** [comment]
@pulsejet I did add the container part above from jellyfin, will the go-vod container accept the runtime and the env accept `nvidia_visible_devices=all`?

**Comment by pulsejet** [comment]
No idea; as I mentioned I've no experience with this (don't have an NVIDIA card)

**Comment by travisboss** [comment]
Going to ask another question maybe someone else can help.

I looked at the go-transcode this is based on and there is a docker file:
```yaml
ARG GO_TRANSCODE_IMAGE=go-transcode:latest
ARG BASE_IMAGE=willprice/nvidia-ffmpeg

#
# STAGE 1: build executable binary
#
FROM $GO_TRANSCODE_IMAGE as build

#
# STAGE 2: build a small image
#
FROM $BASE_IMAGE as base
WORKDIR /app

ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME; \
    useradd --uid $USER_UID --gid $USERNAME --shell /bin/bash --create-home $USERNAME;

COPY --from=build /app/go-transcode go-transcode
COPY profiles profiles

ENV USER=$USERNAME
ENV NVIDIA_DRIVER_CAPABILITIES=all

EXPOSE 8080
ENV TRANSCODE_BIND=:8080

ENTRYPOINT [ "./go-transcode" ]
CMD [ "serve" ]

```

Could I edit this go-vod docker file to include the nvidia driver capabilities and the base image for nvidia?

**Comment by travisboss** [comment]
One more:

```sh
#!/bin/bash

apt-get update
apt-get remove -y libva ffmpeg
apt-get install -y  build-essential yasm cmake libtool libc6 libc6-dev unzip wget libnuma1 libnuma-dev

mkdir qsvbuild
cd qsvbuild

git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
cd nv-codec-headers
sudo make install
cd ..

git clone --depth 1 --branch n6.0 https://github.com/FFmpeg/FFmpeg
cd FFmpeg
./configure --enable-nonfree --enable-cuda-nvcc --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --disable-static --enable-shared
make -j"$(nproc)"
sudo make install
sudo ldconfig
cd ..

cd ..
rm -rf qsvbuild

rm -rf /var/lib/apt/lists/*
```

This is so far building correctly, so a second docker file might be workable?

**Comment by travisboss** [comment]
Getting this error in nextcloud now:

```
Trying go-vod from /config/www/nextcloud/apps/memories/exiftool-bin/go-vod-amd64
go-vod is installed!

You can use transcoding and HLS streaming
This is recommended for better performance, but has implications if
you are using external storage or run Nextcloud on a slow system.

Read the following documentation carefully before continuing:
https://github.com/pulsejet/memories/wiki/Configuration

Do you want to enable transcoding and HLS? [Y/n]


Starting ffmpeg feature detection
This may take a while. Please be patient

Downloading test video file ... OK

Attempting to start go-vod ... OK
go-vod logs will be stored at: /tmp/memories/ocp61gswjh00.log

Testing transcoding with CPU ... FAIL
CPU transcoding failed with error HTTP status: 500
Check the log file of go-vod for more details (/tmp/memories/ocp61gswjh00.log)

Checking for VAAPI acceleration (/dev/dri/renderD128) ... NOT FOUND

Checking for NVIDIA acceleration with NVENC
Testing transcoding with NVENC (scale_npp) ... FAIL
Testing transcoding with NVENC (scale_cuda) ... FAIL
NVENC does not seem to be available

Feature detection completed

Transcoding and HLS are now enabled! Monitor the log file for any errors
You should restart the server for changes to take effect
```

**Comment by pulsejet** [comment]
Side note: if you are using external go-vod then you don't have to run video-setup. Just configure it manually.

**Comment by travisboss** [comment]
@pulsejet so in nextcloud do I just  need to add
```
  'memories.vod.external' => true,
  'memories.vod.connect' => 'go-vod:47788',
```
And nothing else?  Is there any way I can see if it is in fact using nvidia card in the logs?

**Comment by pulsejet** [comment]
No, they just generate the json config.

**Comment by shperrung** [comment]
Build your own image with nextcloud, nvidia stuff and ffmpeg. You just need to check row #20 and set preferable Nextcloud base image.
[Dockerfile.txt](https://github.com/pulsejet/memories/files/11152863/Dockerfile.txt)
My Memories works fine and it uses hw nvidia transcoding. Look on my docker compose stack how to expose nvidia into container 
[nc_db_redis_docker-compose.yml.txt](https://github.com/pulsejet/memories/files/11152902/nc_db_redis_docker-compose.yml.txt)

**Comment by travisboss** [comment]
> Build your own image with nextcloud, nvidia stuff and ffmpeg. You just need to check row #20 and set preferable Nextcloud base image. [Dockerfile.txt](https://github.com/pulsejet/memories/files/11152863/Dockerfile.txt) My Memories works fine and it uses hw nvidia transcoding. Look on my docker compose stack how to expose nvidia into container [nc_db_redis_nvidia_docker-compose.yml.txt](https://github.com/pulsejet/memories/files/11152926/nc_db_redis_nvidia_docker-compose.yml.txt)
> 
> In that option you don't need in external go-vod. Just follow with that recommendations https://github.com/pulsejet/memories/wiki/System-config-options After manual modifying config.php do restart of Nextcloud. HW transcode will be available.

@shperrung are you using nvidia-docker?

**Comment by shperrung** [comment]
> are you using nvidia-docker? I am using linuxserver, are you just using a local build instead of there image?

Unclear question. 
I manually build my own (local) docker image using official "nextcloud:25.0.3-apache" (any version, even "latest") as "base image". Ffmpeg with nvidia cuda stuff and necessary dependencies are built in another "devel" image and then all this is copied into "base image".

**ffmpeg** build process is performed in another official image "nvidia/cuda:11.4.1-devel-ubuntu20.04", where all required nvidia drivers and libraries are installed. This image is about 6Gb. 

I snatched main part of Dockerfile from Julien Rottenberd project https://github.com/jrottenberg/ffmpeg and just replaced base image to "nextcloud:25.0.3-apache". You can change it to your preferable image like "linuxserver/nextcloud" in row20 of Dockerfile

**Comment by pulsejet** [comment]
@shperrung any easy way we could bundle all nvidia stuff into an "official" go-vod Dockerfile (we do that currently for VA-API [here](https://github.com/pulsejet/go-vod/blob/master/Dockerfile)).

Relevant: https://github.com/pulsejet/go-vod/issues/8

**Comment by WGandy** [comment]
> 
> Anyway, all that is needed for creating Nextcloud with FFMPEG supporting HW transcode on Nvidia in docker I gave in my reply above.

Thanks for your contributions here. But I'm not completely following. It seems that you create your Nextcloud image using the docker file that you posted. But does that build correctly when "DEBIAN_FRONTEND=nonintercative" is mispelled twice in the file? 
Also, your docker-compose file looks like it would pull from the Nextcloud docker hub repository. Feel free to call me ignorant about building images with a Dockerfile, but I would love to use this opportunity to learn more about it. It seems like we should be able to build the image with docker compose rather than doing that step separately? Any chance that you can spell out the steps with just a little more detail? (I think I'm close but just need a couple hints).

**Comment by shperrung** [comment]
> "DEBIAN_FRONTEND=nonintercative" is mispelled twice in the file?

Hi!
Yes, surprisingly it works. I think, that Docker ignores that ENV because there all interactive shell commands have attached responses like "-y", therefore we haven't errors.

> Also, your docker-compose file looks like it would pull from the Nextcloud docker hub repository

Right, I don't know any others way to "inject" ffmpeg into nextcloud image. I get ready for service "nextcloud:25.0.3-apache" image and just copy ffmpeg with dependencies from another image:
**FROM    nvidia/cuda:11.4.1-devel-ubuntu20.04 AS devel-base** - in that command we get the image with pre-installed Cuda-nvidia-toolkit and install packages required for building from sources.
"AS devel-base" means, that we name this image as "devel-base". 
If you look next commands you will see that "FROM  devel-base as build" - it means that we rename image to "build" but it remains the same. I don't know why JRottenberg, who is an author of original Dockerfile, uses that renames, but I decided do not change while it works.
And here, in "build" image we build ffmpeg and all dependencies.
In the beginning we get
"FROM        nextcloud:25.0.3-apache AS runtime-base" original nextcloud image and give'm name "runtime-base". Than we install here some required packages. At the end of building we again rename it:
"FROM        runtime-base AS release" and copy here all "ffmpeg+dependencies" compiled files into target folders from "build" image. I added some required libraries to support` HW **npp** scale filter.

Sometimes I got errors related to sources availability. Typical command block which compile package from sources looks like this

`##        curl -sL https://download.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-${X264_VERSION}.tar.bz2 | \
        curl -sL http://www.slackel.gr/repo/source/extra/x264/x264-snapshot-20170225-2245-stable.tar.bz2 | \
        tar -jx --strip-components=1 && \
        ./configure --prefix="${PREFIX}" --enable-shared --enable-pic --disable-cli && \
        make && \
        make install && \
        rm -rf ${DIR}`

https://download.videolan.org/pub/ - was unavailable onetime and I replaced it with http://www.slackel.gr/repo/source/... (using Google search)

> It seems like we should be able to build the image with docker compose rather than doing that step separately?

I didn't test it and mostly I'm using Portainer for docker-compose "up". I don't know how image building works in Portainer stacks manager. Also I don't think that it is reasonable because people uses different docker-compose.yml for nextcloud stacks.

**Comment by shperrung** [comment]
@pulsejet 
> any easy way we could bundle all nvidia stuff into an "official" go-vod Dockerfile

I think yes. My Dockerfile do 2-stage build. It is possible to replace nextcloud image with simple Ubuntu image as "release-base" and add 3rd stage with build of go-vod.
It better to use my Dockerfile as base for modification and add "go-vod" part there, because it is more complex and also it avoids from mistakes. Also I can try to simplify my Dockerfile: remove SHA checksum check, define exact versions for sources and reduce compilation blocks. I don't think that we need to follow with latest versions of ffmpeg and other dependencies. Let we use versions, that really works without errors and warnings until it's supported by host system and Nvidia drivers.

**Comment by shperrung** [comment]
Hi!
Latest Cuda Toolkit crashes my Nextcloud container based on custom image re-built with ffmpeg supporting nvidia HW transcode. Be careful while update your system. Make system backup before update.

Still can't start digging in creating ext go-vod with ffmpeg_cuda.

**Comment by shperrung** [comment]
Hi!
Just tried to use external go-vod with Memories and Nvidia P400 Quadro with no success:
- OS: Debian 11 (OpenMediaVault)
- Browser: Firefox
- Memories Version: 5.1.0
- Nextcloud Version: Nextcloud-apache-25.0.7 in Docker
- PHP Version: 8.1.20

Nice webgui for Memories. For "External go-vod" I built separately docker image as per instruction here https://github.com/pulsejet/go-vod/blob/master/Dockerfile.nvidia
then I added go-vod service into my Nextcloud docker-compose stack (I don't use build instruction inside docker-compose.yml preferring to make image separately)
`  go-vod:
     image: go-vod:latest
     restart: always
     environment:
      - NVIDIA_VISIBLE_DEVICES=ALL
     devices:
      - /dev/nvidiactl:/dev/nviiactl
      - /dev/nvidia0:/dev/nvidia0
     volumes:
      - ncdata:/var/www/html:ro
volumes:
  ncdata:`

When I turn on "External Transcoder (go-vod) I see warn "go-vod failed test: version does not match 0.1.7 <==> 0.1.1. "
And video isn't played.

**Comment by pulsejet** [comment]
@shperrung you need to either use the correct tag of go-vod (0.1.1) or use the alpha version of memories (better)

**Comment by pulsejet** [comment]
Stale. New instructions at https://memories.gallery/hw-transcoding/
