### ISSUE TITLE
places-setup results in Allowed memory exhausted

### ISSUE THREAD

**Issue by dugite-code** [pulsejet/memories#575]
**Describe the bug**
When running the `php occ memories:places-setup` results in memory exhausted error increasing the memory limit to 3 gigs with `php -d memory_limit=3G occ memories:places-setup` results in a longer run but still errors out.

**Platform (please complete the following information):**

- OS: Debian system running latest [Nextcloud docker](https://github.com/nextcloud/docker)
- Version:  Memories 5.0.0 - Nextcloud 26.0.0

**Additional context**
```
Inserted 230500 / 635189 places (36.3%), Last: Kupti
PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/custom_apps/memories/lib/Service/Places.php on line 208
PHP Fatal error:  Allowed memory size of 3221225472 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/lib/private/Log/LogDetails.php on line 82
```

**Comment by pulsejet** [comment]
1. Can you provide more information about the setup? E.g. database, memcache etc.
2. There's no memleak in the script itself, so this is coming from somewhere else. Can you try adding the following lines after the `Inserted {$count} ...` line in `/memories/lib/Service/Places.php`?
```php
// print memory usage
$mem = round(memory_get_usage() / 1024 / 1024, 2);
echo "Memory usage: {$mem} MB\n";

// force garbage collection
gc_collect_cycles();
```
3. Try restarting the server.

**Comment by dugite-code** [comment]
Ok turns out this was me not cleaning up after copying from my testing. I had the profiler enabled in the config `'profiler' => true` and even though the app js wasn't built and I had disabled the app via occ it was chewing up memory on the PHP side of things.

Terribly sorry for the noise

**Comment by TtuxX** [comment]
Hi there @pulsejet ! 

I am experiencing the same Allowed memory exhaustion issue on Freebsd (Truenas 13) and cannot edit EXIF data.
Furthermore this error happens when cron job is running, provoking unexpected cron exit with the following error:

`[PHP] Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 5618384 bytes) at /usr/local/www/nextcloud/apps/maps/lib/Helper/ExifGeoData.php#120`

I am also having this issue (not sure if it is related):

`{"reqId":"ZO0W0atHtnNGJyt8nbed","level":3,"time":"2023-04-26T14:29:32+00:00","remoteAddr":"192.168.1.254","user":"xxxx","app":"index","method":"GET","url":"/apps/memories/api/system-status","message":"Path cannot be empty in file '/usr/local/www/nextcloud/apps/memories/lib/Service/BinExt.php' line 35","userAgent":"xxxx","version":"25.0.6.1","exception":{"Exception":"Exception","Message":"Path cannot be empty in file '/usr/local/www/nextcloud/apps/memories/lib/Service/BinExt.php' line 35","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Memories\\Controller\\OtherController"],"getSystemStatus"]},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Memories\\Controller\\OtherController","getSystemStatus",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["memories.Other.getSystemStatus"]]},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1048,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/memories/api/system-status"]},{"file":"/usr/local/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"ValueError","Message":"Path cannot be empty","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/apps/memories/lib/Service/BinExt.php","line":35,"function":"copy","args":["","/tmp//exiftool-ocl971a0478l-12.58-d41d8cd9"]},{"file":"/usr/local/www/nextcloud/apps/memories/lib/Service/BinExt.php","line":97,"function":"getTempBin","class":"OCA\\Memories\\Service\\BinExt","type":"::","args":["","exiftool-ocl971a0478l-12.58"]},{"file":"/usr/local/www/nextcloud/apps/memories/lib/Controller/OtherController.php","line":125,"function":"getExiftoolPBin","class":"OCA\\Memories\\Service\\BinExt","type":"::","args":[]},{"file":"/usr/local/www/nextcloud/apps/memories/lib/UtilController.php","line":20,"function":"OCA\\Memories\\Controller\\{closure}","class":"OCA\\Memories\\Controller\\OtherController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/local/www/nextcloud/apps/memories/lib/Controller/OtherController.php","line":193,"function":"guardEx","class":"OCA\\Memories\\Util","type":"::","args":[["Closure"]]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getSystemStatus","class":"OCA\\Memories\\Controller\\OtherController","type":"->","args":[]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Memories\\Controller\\OtherController"],"getSystemStatus"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Memories\\Controller\\OtherController"],"getSystemStatus"]},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Memories\\Controller\\OtherController","getSystemStatus",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["memories.Other.getSystemStatus"]]},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1048,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/memories/api/system-status"]},{"file":"/usr/local/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/www/nextcloud/apps/memories/lib/Service/BinExt.php","Line":35},"CustomMessage":"--"},"id":"6449358edf5bd"}`

ALso, I cannot input the exif binary path in the Memories admin panel as the field is not editable, whether I activate system's perl alternative option.

**Comment by pulsejet** [comment]
```
/usr/local/www/nextcloud/apps/maps/lib/Helper/ExifGeoData.php#120
                              ^^^^
```
This is not related to Memories, it's the Nextcloud maps app.

The other issue is fixed on master.

**Comment by TtuxX** [comment]
Ooops sorry!! 😵‍💫 I was too focus on Exif modification issue that was happening to me when using your app, my bad.
Awasome, thank you so much !! :)
