### ISSUE TITLE
Can't scroll to the end via scrollbar on IOS webapp

### ISSUE THREAD

**Issue by w00lfy** [pulsejet/memories#584]
First, thank you soooo much for the fantastic work with Memories. I love the app!

**Is your feature request related to a problem? Please describe.**
Using Memories in a Webapp with my mobile phone, an Iphone 13, I cannot scroll all the way down to the last image using the sidebar in Timeline View. This is because the screen has rounded edges which the app does not account for. This means that I can only scroll about 80% to the bottom of the page before my finger is off the screen and it does not scroll any longer.

Notably, this is NOT a problem when I open the app/webpage via any browser but only when I add it to my homescreen as a webapp (because in that case, there are no bars at the bottom of the screen).

**Describe the solution you'd like**
Ideally, the scroll sidebar in Timeline View is shortened or rather "compressed" somewhat so it does not cover the 100% height of the (mobile) screen. Personally, I believe that the same adaptation would also add to UX for desktop view.

**Comment by vitis586** [comment]
I tried it on iPhone 13 Pro and the timeline scroll did not let me go all the way. I had to use the old-school screenshot way, because the rounded corners are not visible on on-device screenshots. 😄 
![obrazek](https://user-images.githubusercontent.com/55784861/232859555-2ff4f485-0304-4f8d-9733-79ae4cc5b504.png)
On Pixel 7 Pro it does let me scroll all the way to the bottom even though there are rounded corners too and there is some bottom bar (see below). But the radii is a bit smaller. Screenshot is not taken all the way down.
![obrazek](https://user-images.githubusercontent.com/55784861/232861392-080dde9b-1e53-4627-abf3-cd9391e65b41.png)
On both devices there is a problem with coming back up. When the drag feature (the circle with arrows up and down - I bet there is a name for it) is at the very bottom, you can't grab it really. Phones always try to minimize the app - they register dragging from bottom gesture. You have to scroll a bit up and then you can grab it.

**Comment by pulsejet** [comment]
LMAO 🤣
Wonder if Apple thought about this when they curved the screen.

**Comment by pulsejet** [comment]
Should be fixed on master now.

![image](https://github.com/pulsejet/memories/assets/10709794/228346c2-1a93-4933-bc2a-8ce0d9ad5541)
