### ISSUE TITLE
Memories, go-vod and TrueNAS/FreeBSD

### ISSUE THREAD

**Issue by pixel8383** [pulsejet/memories#617]
I installed Memories on a Nextcloud installation running on TrueNAS13 / FreeBSD13.1 but the can't run the Video Transcoding feature.

The issue seems to be related to the go-vod-amd64 binary which - as far as I understood - runs on linux only. Is that true?

Is there any workaround to enable video transcoding on my installation setup?

**To Reproduce**
1. Install Memories
2. Try to run the go-vod-amd64 file using `/usr/local/www/nextcloud/apps/memories/exiftool-bin/go-vod-amd64` via SSH.
3. The result will be:
```
ELF binary type "0" not known.
/usr/local/www/nextcloud/apps/memories/exiftool-bin/go-vod-amd64: Exec format error. Binary file not executable.
```

Confirming that the binary is not the proper one for the choosen platform.

**Platform (please complete the following information):**

- OS: TrueNAS 13 / FreeBSD 13.1-RELEASE

**Comment by invario** [comment]
Give me a few, the steps will take me a bit of time to write out and make sure are correct also.

**Comment by invario** [comment]
In order to get go-vod working in your FreeBSD jail, you have to compile it yourself.

Create a new jail. I always have a clone jail ready to go called "testjail" for me to test things (services, settings, etc.). That way if I break something, I can just destroy the jail and create a new one and start over. In this case, we are using it to compile go-vod.

From a terminal/SSH/console - open a terminal into the jail:
`iocage console testjail`

Install go and git. These are needed to compile go-vod. If this is your first time installing a pkg in this jail, it will give you some messages about updating packages, etc. etc. just proceed.
`pkg install go git`

Create a working directory so you don't make a mess anywhere.  I just make a folder in root for my testing.
```
mkdir /root/test
cd /root/test
```

Clone go-vod into the directory
`git clone https://github.com/pulsejet/go-vod`

Switch to the new go-vod directory:
`cd /root/test/go-vod`

Set the required environment variable before compiling as per instructions from the author. (Note: If your shell is not csh (it should be unless you set your jail to use something else), then use export instead to set the environment variable.)
`setenv CGO_ENABLED 0`

Compile go-vod.
`go build -ldflags="-s -w"`

You should now have a "go-vod" binary compiled in the folder.  Test it by executing:
`./go-vod`

You should get something like this:
```
&{Configured:false Bind::47788 FFmpeg:/usr/local/bin/ffmpeg FFprobe:/usr/local/bin/ffprobe TempDir:/tmp/go-vod ChunkSize:3 LookBehind:3 GoalBufferMin:1 GoalBufferMax:4 StreamIdleTime:60 ManagerIdleTime:60 VAAPI:false VAAPILowPower:false NVENC:false NVENCTemporalAQ:false NVENCScale:}
2023/04/26 18:34:21 Starting VOD server

```
If you do, you are set!  Control-C to terminate it. Exit your jail's console but remain in your TrueNAS console.

copy the compiled go-vod binary you just compiled from your testjail into your NC root home folder
`cp /mnt/MYPOOL/iocage/jails/TESTJAIL/root/root/test/go-vod/go-vod /mnt/MYPOOL/iocage/jails/NCSERVERJAIL/root/root`

Open a console into your NC jail
`iocage console NCSERVERJAIL`

Copy your go-vod binary somewhere that your www user has access to so that your web server can execute it. I like to place it into the same place all the prepackaged binaries are from Memories but NOTE that whenever you update Memories, the binary will be deleted and you will have to copy it again. You may want to place the file elsewhere accessible by www.
`cp /root/go-vod /usr/local/www/nextcloud/apps/memories/exiftool-bin/go-vod-custom`

Give ownership of the file to the web user... or otherwise set permissions appropriately. I just change ownership.
`chown www:www go-vod-custom`

Edit your NC server config (config.php). I like using ee for my editor
`ee /usr/local/www/nextcloud/config/config.php`

Edit or add the following line as needed:
`'memories.vod.path' => '/usr/local/www/nextcloud/apps/memories/exiftool-bin/go-vod-custom',`

And that should be it. No jail or service restarts needed.

**Comment by pixel8383** [comment]
Thank you very much @invario, you made it super-easy! It worked like a charm. I see a CPU spike while transcoding but it's fast enough to be effective.

I am not sure if it's not more convenient to keep the Go-VoD jail instead of moving the files. This way you should configure the VoD service as external and you will be safe when upgrading the Memories app.

**Comment by invario** [comment]
That's great! What CPU do you have and what kind of videos are you transcoding? I wish my server could keep up.

Yeah,  you can probably run go-vod in its own jail and that way it will persist even when you update Memories. But I would just put the binary somewhere else in the same jail that won't get deleted when you update. Seems a bit excessive to run an entire jail just for go-vod.

**Comment by pixel8383** [comment]
Yep, your idea could work too. I have no access to that nextcloud installation right now but if I am not wrong the CPU is a (not-so-special) 4-core AMD and TrueNAS (which is hosting Nextcloud) has 24GB of ram. I tested the functionality this morning with some random full-HD videos.

**Comment by invario** [comment]
Okay, that makes sense. Yeah, my server can keep up with 1080p30FPS no problem.

But most of my content is recorded on my phone at 4K60FPS which uses up a ton more  processing to transcode.

**Comment by invario** [comment]
No worries. Just keep that in mind if you ever do get 4K videos and it's lagging very badly. Nothing wrong with the configuration.... Just not fast enough lol

**Comment by voxlifoxi** [comment]
Update: The git repo above is outdated. The memory app complains about an old version. go-vod moved to the memories repo.

The build step changes to: (inside the test jail) 
```sh
git clone https://github.com/pulsejet/memories.git
cd memories/go-vod
CGO_ENABLED=0 go build -ldflags="-s -w"
```

Btw, I had to restart my jail and delete the `go-vod` folders in `/tmp` (on the host):

```sh
iocage stop NCSERVERJAIL
rm -r /mnt/MYPOOL/iocage/jails/NCSERVERJAIL/root/tmp/go-vod*
iocage start NCSERVERJAIL
```

**Comment by invario** [comment]
Yeah my instructions are super outdated now lol.  I'll update when I have some time. 🙂
