### ISSUE TITLE
Option to re-scan EXIF (etc.) data

### ISSUE THREAD

**Issue by Ra72xx** [pulsejet/memories#766]
**Is your feature request related to a problem? Please describe.**
I have my photos stored in an local external storage. I use another app to manage my photos (DigiKam) and have set this program not to change the file date when modifying an image in order to preserve the original date of a photo also in the file creation date. However, this seems to imply that changed EXIF data sets, e.g. adjusted geotagging, is not picked up after the first scan.

**Describe the solution you'd like**
A simple button (or at least an occ command) to force-rescan the EXIF data of a folder, with an option to do so recursively.

**Describe alternatives you've considered**
occ photos:map-media-to-place
occ files:scan --all
occ maps:scan-photos

**Comment by pulsejet** [comment]
`occ memories:index -f`. But this will rescan the entire library even if you specify a single folder (IIRC)

**Comment by Ra72xx** [comment]
Thanks for the hint. I overlooked that this command also has command line options. I try this.

**Comment by reox** [comment]
This seems to not re-index metadata, for example GPS location.
I re-uploaded some photos to nextcloud with changed EXIF data (added GPS location) but the `memories:index -f` would not pick it up.

I used `occ files:scan --generate-metadata --all`, which however also removed all photos from memories (is that the desired behaviour?!). After running `occ memories:index --force` again, all photos are back and now have the GPS location set.

**Comment by pulsejet** [comment]
`memories:index -f` _should_ pick up any direct changes to the files (otherwise its a bug). The file rescan is possibly changing the file IDs for your file. I'd advise caution: this might destroy your albums and favorite tags.

Regardless, the modified time is supposed to indicate when the file was modified; if you don't follow those semantics then you'll likely run into trouble. Ideally, you should have the creation date _inside_ the file EXIF (this is very easy to achieve with `exiftool` copying over the modification time to the EXIF data), and then let the `mtime` update whenever you change the file. Then it should directly be picked up with `occ files:scan --all` followed by `occ memories:index` (no `-f` needed)
