### ISSUE TITLE
Start playing live/motion photo while loading resource

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#920]
**Is your feature request related to a problem? Please describe.**
This could be the same as #268

**Describe the solution you'd like**
It would be nice if the live/motion photo started to play even before the full mp4/media file was loaded. 

**Describe alternatives you've considered**
Some other applications seem to play the live/motion photo immediately when hovering over them without any delay. 

**Additional context**
I'm not sure how this is achieved from a technical perspective. Perhaps caching like mentioned in #268, but it seems like that would only speed up the playback of the live/motion photo after the first time it is played slowly. Perhaps there's a way to start streaming the live/motion photo before the entire mp4 or video file is retrieved?

If the first-time quick playback of the motion/live photo will be addressed by #268, then please close this issue.

**Comment by pulsejet** [comment]
Indeed this has mostly to do with caching. The streaming of the video is handled by the browser which should play as soon as it gets the first chunk (since we encode with faststart)
https://github.com/pulsejet/memories/blob/697e29e2efa551ef06c008ace5ff20302d7384a6/go-vod/transcoder/stream.go#L194

So the delay largely comes from hardware / ffmpeg initialization and encoding. Caching the video server-side would probably fix this.

**Comment by pulsejet** [comment]
Close in favor of #268
