### ISSUE TITLE
Implement Blurhash or Thumbhash

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#924]
**Is your feature request related to a problem? Please describe.**
Even though Memories is very vast, sometimes scrolling back and forth in the timeline can cause a brief time where the view doesn't show the photos:
![image](https://github.com/pulsejet/memories/assets/10717998/29a39764-2435-4633-bc60-5adc426b8a75)

**Describe the solution you'd like**
To further improve the browsing experience (which is already quite fast), it would be nice if a [blurhash](https://github.com/woltapp/blurhash) or [thumbhash](https://evanw.github.io/thumbhash/) was displayed until the photo (or photo preview) was loaded. IMO this gives photo viewers a much more polished feel since there is an asset to look at while the fuller version is 'lazy loaded'.

**Describe alternatives you've considered**
Be patient for the images to load - it's pretty quick anyway (I do use preview generator with 512x512px size)

**Additional context**
These kinds of image hashes are VERY tiny:
![image](https://github.com/pulsejet/memories/assets/10717998/0c67c3c8-4095-4b22-8da4-3438c5381959)

**Comment by pulsejet** [comment]
That's ... not how it's supposed to look. Did you modify the theme? The thumbnails are supposed to be darker.

**Memories on dark mode** for me:
![image](https://github.com/pulsejet/memories/assets/10709794/c4647863-b06c-4bac-a781-3ddedeff8bae)

**In light mode**:
![image](https://github.com/pulsejet/memories/assets/10709794/7aa583a4-e6e8-493d-95f1-31313eee5da5)

# blurhash

Now regarding blurhash, I actually considered this but it is very debatable if it leads to better UX. This is especially in context of photo-heavy applications (more specifically, where the picture is the primary content). There are two reasons for this:

1. It greatly increases the number of visual shifts in your primary area of focus. Blurhash makes a lot of sense e.g. in a list of restaurants, because the user is reading the names / rating of the restaurant and the photo is a _supporting_ decoration for the main content.
2. It actually makes the app feel less responsive. Basically when you have a blurhash you need a transition to the actual full-resolution image. If that transition is instantaneous / too short, then it creates a jarring experience where something changes too fast. If the transition is slower, this adds _hundreds_ of milliseconds to the perceived load time. On the other hand, loading the full image instantaneously from a placeholder isn't jarring because the placeholder is initially perceived as, well, a placeholder: that would be replaced soon.

Notably, commercial apps don't use blurhash either (no idea about iCloud). I can't claim the above is the reasoning, but I've no doubt it's due to the effectively worse UX rather than them being too lazy to implement it. See examples below.

**OneDrive:**
![image](https://github.com/pulsejet/memories/assets/10709794/1db8ed96-d240-4c49-9f39-9f587ce31923)

**Google Photos:**
![image](https://github.com/pulsejet/memories/assets/10709794/93a69a65-1064-4e93-9985-3cfb850fc447)

**Comment by pulsejet** [comment]
> Ok, yes, I did modify the theme. I'm using the Breeze Dark theme which apparently has the same background color as the image placeholders lol.

Ah, strange they'd do that.

> I'm fine if you want to close this - I see your point. It's just my opinion that it seems less jarring to see colored hashes subtlety change into higher resolution photos, rather than a images loading in a random pattern which causes a 'flickering' effect.

Agree it's subjective. For now I want to stick to the GPhotos / OneDrive way, but this could be reconsidered later.

**Comment by MrRinkana** [comment]
Nextcloud recently added a BlurHash in core that will be used in (for example) the [files app with nc 31](https://github.com/nextcloud/server/pull/47605). Maybe that could be used by memories?

I personally disagree with blurhashes being more attention grabbing, they don't increase the number of transitions (compare placeholder -> thumbnail vs blurhash -> thumbnail) and the transition in itself is less attention-grabbing as the change is smaller. 

If there is a resonable way to make the drawing of blurhashes so fast one in principle can't scroll fast enough they they don't keep up - essentially "making the blurhashes the placeholders" that would be superawesome. My understanding is that the blurhashes are provided together with image metadata, so loading that could be at the same time as thumbnails are being laid out now, no?

Immich has blurhashes which are unfortunately over-used as scrolling back where one just viewed images shows the blur again for some reason, and its seems possible to get placeholder->blushash->thumbnail (which does indeed add a transition), but most of the time it looks good I'd say. One can get a feel for them on the demo they have

Maybe its a good idea to have a small thumbnail icon overlaid the blurhash such that if the loading is very slow for some reason it is clear that the blurhash _is the placeholder_ (make it clear its still loading)..
