### ISSUE TITLE
Albums: Unshare public link, hide Download button

### ISSUE THREAD

**Issue by jwefers** [pulsejet/memories#945]
When i copy a public link and hand it to people, i want to undo that, i.e. invalidate that public link.

Also, i want to "prohibit" downloading by not showing the download button to at least throw off non tech-savvy family members from sharing around photos i entrust them with via a Memories album.

**Describe the solution you'd like**
In the sharing popup of an Album, it should be visible that a public link has been created/copied before, and have a button to un-share/invalidate that link. And a checkbox for "Downloads allowed". Exactly like sharing *folders* in the rest of Nextcloud behaves

**Describe alternatives you've considered**
Using folders instead of albums, but that throws off the internal structure we use, when we just want to share a couple of specific photos with non-NC family users

**Comment by alesrosina** [comment]
I think there should be also a menu item for a list of all shared albums, similar to shared files in Files app.

Otherwise it's hard to keep track of all the shared albums, if you have many.

PS: @jwefers if you open a share dialog, this means there was no shares yet:

![image](https://github.com/pulsejet/memories/assets/5054909/164997af-a702-4752-878e-a17c32f5831f)

and this means it was already shared.

![image](https://github.com/pulsejet/memories/assets/5054909/75dbb352-8102-45f8-b5ab-c1c17fdacfc9)


Clicking on a X will remove the link.
