### ISSUE TITLE
Do I need to re-index all media when updating memories from 5.4.1 to latest?

### ISSUE THREAD

**Issue by akhil1508** [pulsejet/memories#974]
**This is neither a bug report nor a feature request, but I couldn't find info on this by quickly searching (Apologies for inconvenience if any)**

- I use the memories app on a pretty big nextcloud installation with lots of media
- [5.5.0](https://github.com/pulsejet/memories/blob/master/CHANGELOG.md#v550---2023-10-06) brought along some major changes to the `memories` table including some indexes and a new column
- It says in the changelog that 
  - >  It is recommended to run occ memories:index -f after upgrading.
- For me, re-indexing all the files will take a huge amount of time and I cannot afford for users to miss media while the re-indexing happens

- On the other hand, the newer version(s) of memories have introduced lots of cool features( great job btw :smile:  )

- So is it safe for me to update `memories` to latest and just let the re-indexing of all media happen in the background
  - It is critical for me that users should not see their media missing and should be able to use `memories` normally as usual

**Comment by pulsejet** [comment]
IIRC there were some indexing errors in timezones with earlier versions, plus the new fields are needed for the Android app to work correctly. A forced index can happen in the background and shouldn't affect normal usage of the app (no downtime). Just make sure you only run a single thread with `-f`

Unless you run the forced index, the already uploaded media won't be re-indexed. Any new media would be fine, though. Also I recommend upgrading with the cli because the migration can be very slow.

**Comment by akhil1508** [comment]
@pulsejet Thank you for the quick response! Sounds great to hear that this isn't blocking the update :)

> A forced index can happen in the background and shouldn't affect normal usage of the app

The `length` of the `liveid` column in two tables was changed from `256` to `128`. Does this affect any feature even before re-indexing is completed?

**Comment by pulsejet** [comment]
LiveID is practically never that long so it shouldn't matter (the migration would take care of it). IIRC some databases don't like columns longer than 255, which is why this change.

**Comment by akhil1508** [comment]
@pulsejet Perfect, Thanks! Can close this issue as all is clear now.
